### ISSUE TITLE
[Feature request] Add Google Gemini check

### ISSUE THREAD

**Issue by NastyaGrifon** [xykt/IPQuality#10]
Google Gemini offers similar functionality to ChatGPT and is also IP/Geoblocked.

Adding Google Gemini to `Accessibility check for media and AI services` would benefit the same users looking for VPS/VPN solutions to access Google Gemini and ChatGPT.

**Comment by xykt** [comment]
This feature will be supported by [another script](https://github.com/xykt/RegionRestrictionCheck) later.

**Comment by xykt** [comment]
Done!
Repo: https://github.com/xykt/RegionRestrictionCheck
Command: ```bash <(curl -L -s Media.Check.Place) -E```
