### ISSUE TITLE
Missing array special_ips

### ISSUE THREAD

**Issue by NastyaGrifon** [xykt/IPQuality#11]
This line uses `special_ips` array that is not declared.

https://github.com/xykt/IPQuality/blob/00d20778d3fcb407fb7bd006c243b185eff5ab17/ip.sh#L1054

Not entirely sure what this block of code does, but it must be not working and never raises any errors since it is never used. 

That code block can be cut or refactored to actually work if you clarify what it does

**Comment by xykt** [comment]
That was test code, now deleted. Thank you!
