### ISSUE TITLE
不同测试脚本结果不一

### ISSUE THREAD

**Issue by YangHaoNing-CN** [xykt/IPQuality#13]
https://www.nodeseek.com/post-122017-1
像这里的不同脚本测试不一样，请问这是为何呢

**Comment by xykt** [comment]
可能是测试环境/测试时间的不同造成的，具体请咨询贴主

**Comment by YangHaoNing-CN** [comment]
![image](https://github.com/xykt/IPQuality/assets/83169812/08144e93-6bfa-4d4d-9727-6ec517979309)
这个服务器中Spotify解锁不同
![image](https://github.com/xykt/IPQuality/assets/83169812/1074f7ce-4f18-410f-b895-aa31ef7e1964)
25端口检测也不同

**Comment by YangHaoNing-CN** [comment]
![image](https://github.com/xykt/IPQuality/assets/83169812/274e2c02-91f3-4c9c-a1b8-6c7a390329f9)

**Comment by xykt** [comment]
感谢反馈！
1. 图1麻烦告知哪一个测试结果是准确的
2. 图2邮件这一部分，本脚本是模拟邮件服务器，针对本地及各邮件服务商进行连通性测试，而你提供的脚本我简单看了一下，是模拟邮件客户端进行测试，两者在测试角色上是不同的
3. 图3 DNS解锁因为是多人共用一个通道，因此有时候解锁服务器至流媒体供应商的连接是不稳定的，如果测试过程中遇到IP切换、丢包、卡顿等问题，可能就会导致测试结果不一致，若多次测试仍然出现冲突结果，麻烦告知哪一个测试结果是准确的

**Comment by YangHaoNing-CN** [comment]
图一中Spotify的解锁如何判定我不清楚,我可以访问官网。
图三中应该是网络波动，现在恢复。

![image](https://github.com/xykt/IPQuality/assets/83169812/d323fc01-0547-4f07-a609-6782da2d4046)
我听说telnet成功就说明本地端口通顺，具体情况我并不清楚

**Comment by YangHaoNing-CN** [comment]
然后我手上的机器貌似从未测出25端口非阻断
