### ISSUE TITLE
add "Openwrt" support

### ISSUE THREAD

**Issue by WFANG12719** [xykt/IPQuality#14]
Not supporting OPENWRT, the most popular home router OS.

root@openwrt:~#bash <(curl -Ls IP.Check.Place)
Detecting operating system...
Unsupported distribution: openwrt

**Comment by NastyaGrifon** [comment]
You can try [https://github.com/lmc999/RegionRestrictionCheck](https://github.com/lmc999/RegionRestrictionCheck)
It has the OpenWRT support
