### ISSUE TITLE
Alpine 系统执行脚本报错

### ISSUE THREAD

**Issue by Micah123321** [xykt/IPQuality#16]
HTTP request sent, awaiting response... 200 OK
Length: 36430715 (35M) [application/octet-stream]
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
########################################################################
                       IP质量体检报告：104.28.*.*
                    bash <(curl -sL IP.Check.Place)
                   https://github.com/xykt/IPQuality
        报告时间：2024-07-01 14:29:16 CST  脚本版本：v2024-06-27
########################################################################
一、基础信息（Maxmind 数据库）
自治系统号：            AS13335
组织：                  CLOUDFLARENET
坐标：                  114°10′33″E, 22°17′3″N
地图：                  https://check.place/22.2842,114.1759,15,cn
城市：                  N/A, 香港
使用地：                [HK]香港, [AS]亚洲
注册地：                [US]美国
时区：                  Asia/Hong_Kong
IP类型：                 广播IP 
二、IP类型属性
数据库：      IPinfo    ipregistry    ipapi     AbuseIPDB  IP2LOCATION 
使用类型：     其他        机房        机房        CDN         CDN     
公司类型：     其他        机房        机房    
三、风险评分
风险等级：      极低         低       中等       高         极高
SCAMALYTICS：  0|低风险
ipapi：         0.27%|低风险
AbuseIPDB：    0|低风险
IPQS：                                                      100|高风险
DB-IP：         |低风险
四、风险因子
库： IP2LOCATION ipapi ipregistry IPQS SCAMALYTICS ipdata IPinfo IPWHOIS
地区：    [HK]    [LU]    [HK]    [HK]    [HK]    [HK]     无     [HK]
代理：     否      否      否      是      否      否      无      否 
Tor：      否      否      否      否      否      否      无      否 
VPN：      否      否      否      是      否      无      无      否 
服务器：   是      是      是      无      否      是      无      是 
滥用：     是      是      是      是      无      是      无      无 
机器人：   否      否      无      是      否      无      无      无 
五、流媒体及AI服务解锁检测
服务商：  TikTok   Disney+  Netflix Youtube  AmazonPV  Spotify  ChatGPT 
状态：     失败     解锁    仅自制    解锁     解锁     解锁     仅APP  
地区：              [HK]     [HK]     [HK]     [HK]     [HK]     [HK]   
方式：              原生     原生     原生     原生     原生     原生   
六、邮局连通性及黑名单检测
本地25端口：阻断
IP地址黑名单数据库：  有效 439   正常 433   已标记 5   黑名单 1
========================================================================
今日IP检测量：517；总检测量：36884。感谢使用xy系列脚本！ 
报告链接：https://Report.Check.Place/IP/2XEN01YWC.svg

awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
awk: bad regex '[�-�]': Invalid regexp
########################################################################
                 IP质量体检报告：2400:c620:11:*:*:*:*:*
                    bash <(curl -sL IP.Check.Place)
                   https://github.com/xykt/IPQuality
        报告时间：2024-07-01 14:29:16 CST  脚本版本：v2024-06-27
########################################################################
一、基础信息（Maxmind 数据库）
自治系统号：            AS150452
组织：                  LANDUPS LIMITED
坐标：                  114°9′57″E, 22°15′28″N
地图：                  https://check.place/22.2578,114.1657,15,cn
城市：                  N/A
使用地：                [HK]香港, [AS]亚洲
注册地：                [HK]香港
时区：                  Asia/Hong_Kong
IP类型：                 原生IP 
二、IP类型属性
数据库：      IPinfo    ipregistry    ipapi     AbuseIPDB  IP2LOCATION 
使用类型：     其他        机房        商业        机房        机房    
公司类型：     其他        机房        商业    
三、风险评分
风险等级：      极低         低       中等       高         极高
SCAMALYTICS：  0|低风险
ipapi：    0.00%|极低风险
AbuseIPDB：    0|低风险
IPQS：         0|低风险
四、风险因子
库： IP2LOCATION ipapi ipregistry IPQS SCAMALYTICS ipdata IPinfo IPWHOIS
地区：    [HK]    [HK]    [HK]    [HK]    [HK]    [HK]     无     [HK]
代理：     否      否      否      否      否      否      无      否 
Tor：      否      否      否      否      否      否      无      否 
VPN：      否      否      否      否      否      无      无      否 
服务器：   是      否      是      无      否      否      无      否 
滥用：     否      否      否      否      无      否      无      无 
机器人：   否      否      无      否      否      无      无      无 
五、流媒体及AI服务解锁检测
服务商：  TikTok   Disney+  Netflix Youtube  AmazonPV  Spotify  ChatGPT 
状态：     失败     解锁    仅自制    中国     屏蔽     解锁     失败   
地区：              [HK]     [HK]     [CN]              [HK]            
方式：              原生     原生                       原生            
六、邮局连通性及黑名单检测
本地25端口：阻断
========================================================================
今日IP检测量：520；总检测量：36887。感谢使用xy系列脚本！ 
报告链接：https://Report.Check.Place/IP/1EIU3JJDM.svg

**Comment by xykt** [comment]
已修复，感谢反馈！
