### ISSUE TITLE
我几台境外的VPS 使用脚本之后油管都显示为中国，有点奇怪，麻烦大佬瞅瞅？

### ISSUE THREAD

**Issue by bihell** [xykt/IPQuality#2]
如题

韩国的截图：
https://bigdata.icu/ip-akile-kr.jpg

圣何塞的截图：
https://bigdata.icu/ip-desi-sj.jpg

**Comment by xykt** [comment]
图片打不开，显示403。你这种情况有可能是谷歌IP被拉到中国了。

**Comment by bihell** [comment]
> 图片打不开，显示403。你这种情况有可能是谷歌IP被拉到中国了。

原来如此~~，那就是送中了
