### ISSUE TITLE
脚本报错，换行符附近出现错误

### ISSUE THREAD

**Issue by sky22333** [xykt/IPQuality#21]
**系统Debian 11**

```
root@vm:~# bash <(curl -Ls IP.Check.Place)
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```

**Comment by Prigoryan** [comment]
You get this if Cloudflare is suspicious of your IP

This should work
```
bash <(curl -Ls https://raw.githubusercontent.com/xykt/IPQuality/main/ip.sh)
```

**Comment by xykt** [comment]
> **系统Debian 11**
> 
> ```
> root@vm:~# bash <(curl -Ls IP.Check.Place)
> /dev/fd/63: line 1: syntax error near unexpected token `newline'
> /dev/fd/63: line 1: `<!DOCTYPE html>'
> ```

已修复
