### ISSUE TITLE
CentOS 9 Stream error

### ISSUE THREAD

**Issue by toxicon** [xykt/IPQuality#22]
OS CentOS 9 Stream

```bash
cat /etc/os-release

NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://issues.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

uname -a

Linux abc.xyz 5.14.0-508.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 15:49:37 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
sudo dnf install epel-release -y

Last metadata expiration check: 1:14:48 ago on Sun 22 Sep 2024 11:00:43 PM MSK.
Package epel-release-9-8.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!

sudo dnf install jq curl bc nmap-ncat bind-utils iproute -y

Last metadata expiration check: 1:08:20 ago on Sun 22 Sep 2024 11:00:43 PM MSK.
Package jq-1.6-17.el9.x86_64 is already installed.
Package curl-7.76.1-31.el9.x86_64 is already installed.
Package bc-1.07.1-14.el9.x86_64 is already installed.
Package nmap-ncat-3:7.92-3.el9.x86_64 is already installed.
Package bind-utils-32:9.16.23-24.el9.x86_64 is already installed.
Package iproute-6.2.0-5.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Run

```bash
bash <(curl -Ls IP.Check.Place) -l en
```

Error:

```
/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'
```

**Comment by xykt** [comment]
Try this https://github.com/xykt/IPQuality/issues/21

**Comment by xykt** [comment]
> OS CentOS 9 Stream
> 
> ```shell
> cat /etc/os-release
> 
> NAME="CentOS Stream"
> VERSION="9"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="9"
> PLATFORM_ID="platform:el9"
> PRETTY_NAME="CentOS Stream 9"
> ANSI_COLOR="0;31"
> LOGO="fedora-logo-icon"
> CPE_NAME="cpe:/o:centos:centos:9"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://issues.redhat.com/"
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> 
> uname -a
> 
> Linux abc.xyz 5.14.0-508.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 15:49:37 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> ```shell
> sudo dnf install epel-release -y
> 
> Last metadata expiration check: 1:14:48 ago on Sun 22 Sep 2024 11:00:43 PM MSK.
> Package epel-release-9-8.el9.noarch is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> 
> sudo dnf install jq curl bc nmap-ncat bind-utils iproute -y
> 
> Last metadata expiration check: 1:08:20 ago on Sun 22 Sep 2024 11:00:43 PM MSK.
> Package jq-1.6-17.el9.x86_64 is already installed.
> Package curl-7.76.1-31.el9.x86_64 is already installed.
> Package bc-1.07.1-14.el9.x86_64 is already installed.
> Package nmap-ncat-3:7.92-3.el9.x86_64 is already installed.
> Package bind-utils-32:9.16.23-24.el9.x86_64 is already installed.
> Package iproute-6.2.0-5.el9.x86_64 is already installed.
> Dependencies resolved.
> Nothing to do.
> Complete!
> ```
> 
> Run
> 
> ```shell
> bash <(curl -Ls IP.Check.Place) -l en
> ```
> 
> Error:
> 
> ```
> /dev/fd/63: line 1: syntax error near unexpected token `newline'
> /dev/fd/63: line 1: `<!DOCTYPE html>'
> ```

Fixed
