### ISSUE TITLE
Request to Add/Optimize IPv6-Specific Features.

### ISSUE THREAD

**Issue by Aya-Tatemaru** [xykt/IPQuality#24]
When testing IPv6 connectivity, TikTok, Amazon Prime Video, and ChatGPT always show as 'failed.'

After testing, it was found that ChatGPT and Amazon Prime Video are accessible via IPv6, but TikTok is not.

It is recommended to label entries that cannot be accessed via IPv6 as 'Unable to Detect via IPv6' instead of 'Failed.'

**Comment by xykt** [comment]
Thank you for your suggestion. The script report layout does not provide enough space to display so many characters.
