### ISSUE TITLE
建议去掉 ipapi 这种垃圾数据的检测

### ISSUE THREAD

**Issue by f3liiix** [xykt/IPQuality#26]
我自己买的香港VPS，所有地方检测出来都是香港，唯独ipapi检测出来是新加坡，机房检测不出来是机房、商业也检测不出来是商业，家宽也检测不出来是家宽，结果全显示的“其他”。这种垃圾数据库加上去干嘛。
连IP归属地都整不明白，还指望他能检测出类型呢。放在上面完全影响检测结果的判断和美观性，我真家宽他给我显示的“其他”，搞得客户都疑神疑鬼的。

![GOkryd](https://img.hoofei.com/2024/11/GOkryd.png)

**Comment by xykt** [comment]
感谢反馈，本脚本选取主流数据库进行客观展示，这些数据库的下游客户是各类风控网站。您的意见在后续更新维护中会作为参考。
