### ISSUE TITLE
`/ref/upgrade_bash.sh` Execution Results in Zsh Crash and .bash_profile Deletion

### ISSUE THREAD

**Issue by ManicEuphoria** [xykt/IPQuality#28]
Platform: Apple MacBook M1 Pro
System Version: macOS 15.1
Terminal: iTerm2 with Zsh

### Issue

After running `bash <(curl -Ls IP.Check.Place)`, the terminal reported that my local Bash version (4.x) was insufficient and recommended upgrading.  While I didn't capture the output, the suggested upgrade script was located at `/ref/upgrade_bash.sh`.  Executing this script resulted in a Zsh crash.

### Impact

The upgrade appears to have permanently deleted my `.bash_profile`, resulting in the irreversible loss of my Bash configurations.  Consequently, symbolic links within my `.zshrc` file are now broken, rendering Homebrew, rbenv, and other installed packages unusable.

### Investigation Request

I'd like to understand why the upgrade failed and resulted in the deletion of my configuration files. Please investigate `/ref/upgrade_bash.sh` for potential bugs, as restoring my system to its previous state has been a significant undertaking.

**Comment by ManicEuphoria** [comment]
I've investigated a Bash version parsing issue encountered while using the script on different operating systems.  After forking the repository to debug locally, I discovered an interesting discrepancy between the `bash --version` output on Linux (CentOS 7) and macOS.

The Chinese locale on CentOS 7 adds an extra whitespace character to the first line of the `bash --version` output, which isn't present in the macOS version. This can be demonstrated using the following commands:

CentOS 7:

```bash
uname -a
# Output: Linux ebs-160720 3.10.0-1160.71.1.el7.x86_64 ...
bash --version
# Output (Note extra space after "GNU bash"):
# GNU bash， 版本 4.2.46(2)-release (x86_64-redhat-linux-gnu)
# ...
echo | bash --version | head -n 1 | sed 's/[^ ]//g' | wc -c
# Output: 5 (indicating 5 spaces)
```

macOS:

```bash
uname -a
# Output: Darwin boozerasiaMacBook-Pro.local 24.1.0 ...
bash --version
# Output:
# GNU bash，版本 5.2.37(1)-release (aarch64-apple-darwin24.0.0)
# ...
echo | bash --version | head -n 1 | sed 's/[^ ]//g' | wc -c
# Output: 4 (indicating 4 spaces)
```

This extra space causes the original code (`current_bash_version=$(bash --version|head -n 1|awk '{print $4}'|cut -d'.' -f1)`) to extract incorrect version information on MacOS.  On centOS 7, the output is as expected, just as below:

```sh
# On MacOS
bash --version|head -n 1|awk '{print $4}'|cut -d'.' -f1
# Output:
# (aarch64-apple-darwin24

# On centOS 7
bash --version|head -n 1|awk '{print $4}'|cut -d'.' -f1
# Output:
# 4
```

To address this inconsistency and improve the script's robustness, I've implemented a more reliable method for parsing the Bash version:

```bash
current_bash_version=$(bash --version | head -n 1 | awk -F ' ' '{for (i=1; i<=NF; i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+/) {print $i; exit}}' | cut -d . -f 1)
```

This revised code iterates through the fields of the first line of the `bash --version` output and extracts the first field matching the version pattern (e.g., "X.Y.Z"). This approach handles variations in spacing and ensures consistent version parsing across different systems.

I've tested this solution on both macOS and CentOS 7 and confirmed that it correctly extracts the major Bash version in both cases. I've submitted a pull request with this change. Please let me know if any further modifications are needed.

**Comment by xykt** [comment]
I sincerely apologize for the impact caused. I have an old MacBook Pro 2013, and possibly due to its outdated version, I failed to identify this critical issue, leading to potential major risks.
