### ISSUE TITLE
请问大佬：IP地 址 黑 名 单 数 据 库 ：   有 效  439   正 常  434   已 标 记  4   黑 名 单  1

### ISSUE THREAD

**Issue by jfmeng** [xykt/IPQuality#3]
已标记4是什么意思，和黑名单是什么意思？是被某个网站标记和拉黑了还是中国防火墙？

**Comment by xykt** [comment]
是被数据库标记为某种状态，比如不干净的历史等等，区别于常规Blacklist。但是由于数据库太多400+，各数据库对返回值定义各有不同，脚本无法一一做出解释，因此统一定义为“已标记”。

**Comment by jfmeng** [comment]
好的，感谢解释。
