### ISSUE TITLE
macOS Sonoma 14.5 个别中文乱码

### ISSUE THREAD

**Issue by liangyi9812** [xykt/IPQuality#8]
<img width="532" alt="SCR-20240606-pjdb" src="https://github.com/xykt/IPQuality/assets/6373858/87c945ed-fd7a-4029-8ce8-e8ab9eee76c8">

---

系统自带的终端和 iTerm 出现同样的情况

环境:
<img width="623" alt="SCR-20240606-pjxk" src="https://github.com/xykt/IPQuality/assets/6373858/7e6b934b-d077-4a53-9eeb-fbca922d37e0">

**Comment by xykt** [comment]
感谢反馈，应该是和系统终端语言包设置有关，需调整locale设置。请注意，**本脚本立项原则包括：不下载任何文件/脚本/程序，不更改任何系统设置（含locale），不安装必要依赖以外任何程序**。本脚本已经专门为兼容macOS进行了大量的妥协，包括加入更新bash专门代码，改写所有函数中的grep的-P参数等兼容性问题，**实在无法进一步作出任何突破脚本立项原则的妥协**，敬请理解。欲解决此问题，烦请自行配置优化locale，谢谢！
